### ISSUE TITLE
Is it possible to predict action units?

### ISSUE THREAD

**Issue by tvaranka** [av-savchenko/face-emotion-recognition#47]
In the paper "Frame-level Prediction of Facial Expressions, Valence, Arousal and Action Units for Mobile Devices" predictions are made for AUs. I wonder if this is possible with the code provided here?

**Comment by av-savchenko** [comment]
Thanks for your question. Yes, the [abaw5_expr_va_au_train.ipynb](https://github.com/av-savchenko/face-emotion-recognition/blob/main/src/ABAW/abaw5_expr_va_au_train.ipynb) contains all the required information to reproduce our paper

**Comment by av-savchenko** [comment]
Please, take a look at the above-mentioned ipynb file, there are several markdown comments after section "AU (Action Units)" that compare performance for several pre-trained models. I believe, enet_b0_8_best_vgaf works better

**Comment by tvaranka** [comment]
Thanks a lot!
