### ISSUE TITLE
Retrieving facial action units

### ISSUE THREAD

**Issue by Fe-56** [av-savchenko/face-emotion-recognition#53]
Hello there, thank you for the amazing work!

May I know if there is any API or function for me to retrieve the facial action units from a image/video file? 

Thank you!

**Comment by av-savchenko** [comment]
Hello! Unfortunately, I do not have any reasonable model for AU detection. There are some examples to train a model using datasets from ABAW competition: [MTL ABAW-7](https://github.com/av-savchenko/face-emotion-recognition/blob/main/src/ABAW/ABAW7/mtl.ipynb) and [AU ABAW-6](https://github.com/av-savchenko/face-emotion-recognition/blob/main/src/ABAW/ABAW6/abaw6_affwild2.ipynb) but I'm not sure that these models are robust enough to make them publicly available
